### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jowbjj** [FazioNico/easymoneymanager#1]
Error while executing ionic serve

Runtime Error
Cannot find module "../providers/fb-config"
Stack
Error: Cannot find module "../providers/fb-config"
    at Object.560 (http://localhost:8100/build/main.js:1262:7)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.461 (http://localhost:8100/build/main.js:1235:70)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)
    at http://localhost:8100/build/main.js:1:1

**Comment by jvcsizilio** [comment]
I got the same error. Any solution?

**Comment by FazioNico** [comment]
@jvcsizilio the missing file is just your firebase config object as exportable. 
And i dont know if the project still work cause is not updated with the latest dependecies.
Enjoy
